#!/bin/bash -e

until [ -d .git ] ; do
    if [ `pwd` == '/' ] ; then
        echo "Couldn't find Git repo. Exiting..."
        exit
    fi
    cd ..
done

echo "syncing branch with $(basename `pwd`)/develop"

source "$(git --exec-path)/git-sh-setup"

BRANCH="develop"
if [ "$1" != "" ] ; then
    BRANCH=$1
fi

if [[ $(git diff --shortstat) ]] ; then
    STASH="POP"
    git stash
fi
git fetch
git rebase origin/${BRANCH}
if [ "${STASH}" == "POP" ] ; then
    git stash pop
fi
