#!/bin/bash -e

source "$(git --exec-path)/git-sh-setup"

BRANCH="develop"
if [ "$1" != "" ] ; then
    BRANCH=$1
fi

if [[ $(git diff --shortstat) ]] ; then
    STASH="POP"
    git stash
fi
git fetch
git rebase origin/${BRANCH}
if [ "${STASH}" == "POP" ] ; then
    git stash pop
fi
